version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'github-actions'

  # dashboard (Node.js)
  - package-ecosystem: 'npm'
    directory: '/dashboard'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'npm'
      - 'dashboard'
    versioning-strategy: increase

  # api (Node.js)
  - package-ecosystem: 'npm'
    directory: '/api'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'npm'
      - 'api'
    versioning-strategy: increase

  # Root (Node.js)
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'npm'
      - 'root'
    versioning-strategy: increase

  # react-spa (Node.js)
  - package-ecosystem: 'npm'
    directory: '/react-spa'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'npm'
      - 'react-spa'
    versioning-strategy: increase

  # shared (Node.js)
  - package-ecosystem: 'npm'
    directory: '/shared'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'npm'
      - 'shared'
    versioning-strategy: increase

  # firefox-extension (Node.js)
  - package-ecosystem: 'npm'
    directory: '/firefox-extension'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'npm'
      - 'extension'
    versioning-strategy: increase
